Step2 문자열 계산기
Effective-Tilinkle/racingcar-with-java pull request #5
Opened 2023-01-20 00:23 UTC by KimJeongHoon3

- 요구사항
  - 사용자가 입력한 문자열 값에 따라 사칙연산을 수행할 수 있는 계산기를 구현해야 한다. (+,-,/,*)
   - 입력 문자열의 숫자와 사칙 연산 사이에는 **반드시 빈 공백 문자열**이 있다고 가정한다.
  - **나눗셈의 경우 결과 값을 정수**로 떨어지는 값으로 한정한다.
  - 문자열 계산기는 **사칙연산의 계산 우선순위가 아닌 입력 값에 따라 계산 순서가 결정**된다. 즉, 수학에서는 곱셈, 나눗셈이 덧셈, 뺄셈 보다 먼저 계산해야 하지만 이를 무시한다.
- 구현내용
  - `Calculator` : client로 부터 계산기 동작을 요청받는 서비스
  -  `Operator` : 연산자의 종류 및 실질적인 연산동작을 가진 enum

2023-01-20 00:53 UTC, makga87 commented on src/main/java/calculator/Calculator.java
> +        };
[Good] 이렇게 미리 선언하는 방법이 있었군요, 너무 좋네요, 기존 코드에서도 매번 호출 시, Enum에서 loop로 찾는 메서드들이 종종 있는데, 앞으로는 위 코드를 애용하게 될 것 같습니다.

2023-01-20 00:53 UTC, makga87 commented on src/main/java/calculator/Calculator.java
> +                throw new IllegalArgumentException("abnormal operator");
[Request-Request] 예외메시지 첫 글자는 대문자가 어떨까요? 단순히 에러메시지이긴 하지만, 일단은 문장이니만큼...

2023-01-20 00:53 UTC, makga87 commented on src/main/java/calculator/Calculator.java
> +    }
[Major-Discussion] 단순히, 연산자 기준으로 계산을 하면, 사칙연산의 우선계산 순위가 제대로 동작하지 않을 것으로 보입니다. 
수정이 필요해보이네요 :)

P.S : To. 노션 STEP2 요구 조건에는 없어 보입니다만, 괄호가 있다면, 괄호 연산먼저 진행해야할 텐데, 괄호는 입력되지 않는다가 전제일까요?

2023-01-20 00:53 UTC, makga87 commented on src/test/java/calculator/CalculatorTest.java
> +        assertEquals(10, Calculator.calculate(target));
[Majon-Request] 위 사칙연산 우선순위 내용과 동일합니다.
곱셈/나눗셈 우선 계산 후, 덧셈/뺄셈을 하므로, expected 값은 10이 아닌 8이 될 것 같네요

2023-01-20 00:59 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +    }
@makga87 요구사항 4번째에 사칙연산 우선계산은 고려하지않는다고해서 단순하게 만들었습니다~ 그래서 괄호 관련해서도 당연히 없을줄알았어서.. 한번 확인해보겠습니다~ 

@pjhsk113 장호님 혹시 괄호도 고려대상일까요??

2023-01-20 01:00 UTC, pjhsk113 commented on src/main/java/calculator/Calculator.java
> +    }
Step2 요구사항은 괄호나 우선순위 계산은 제외입니다~!!

2023-01-20 01:03 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +                throw new IllegalArgumentException("abnormal operator");
@makga87 넵 대문자 반영하였습니다~
53220f8

2023-01-20 01:32 UTC, pjhsk113 commented on src/main/java/calculator/CalculatorMain.java
> +        System.out.println(Calculator.calculate(str));
[Recommend-Major]
입력과 출력을 담당하는 별도의 클래스가 있으면 좋겠네요~
`InputView`, `ResultView`

2023-01-20 01:32 UTC, pjhsk113 commented on src/main/java/calculator/Calculator.java
> +    enum Operator {
[Recommend-Major]
별도의 클래스로 분리하는건 어떨까요~??

2023-01-20 01:32 UTC, pjhsk113 commented on src/main/java/calculator/Calculator.java
> +        DIVIDE("/", (a, b) -> a / b),
[Major-Must]
입력 인자로 0, 0이 들어온다면 ArithmeticException이 발생할 것 같네요!

2023-01-20 01:32 UTC, pjhsk113 commented on src/main/java/calculator/Calculator.java
> +        private final BiFunction<Integer, Integer, Integer> calculationFunction;
[GOOD]
함수형 인터페이스를 활용해 깔끔한 연산 작업을 만드셨네요👍
한 가지 코멘트를 드리자면 BiFunction<Integer, Integer, Integer>와 `BinaryOperator<Integer>`는 같은 역할을 할 수 있어요!
BiFunction<T,U,R>은 두 개의 입력 값(T, U)를 받아서 R 타입을 리턴하는 함수형 인터페이스입니다.
만약 입력값과 리턴값이 모두 같은 타입이라면 `BinaryOperator<T>`를 사용할 수 있습니다~!

2023-01-20 01:32 UTC, pjhsk113 commented on src/test/java/calculator/CalculatorTest.java
> +        assertEquals("Target must not null or not empty", illegalArgumentException.getMessage());
[Recommend-Request]
assertJ를 활용해 더 표현력있는 테스트를 만들어보는건 어떤가요~?
```java
assertThatThrownBy(() -> Calculator.calculate(target))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("Target must not null or not empty");
```

2023-01-20 04:09 UTC, KimJeongHoon3 commented on src/main/java/calculator/CalculatorMain.java
> +        System.out.println(Calculator.calculate(str));
@pjhsk113 해당 클래스는 제거해야했는데, 못했네요. 계산기라는 모듈을 제공하는거라 생각했는데, 혹시 View 관련한 클래스가 필요할까요?

2023-01-20 04:15 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +    enum Operator {
혹시 별도 클래스 분리가 어떤 사유에서 요청주신걸까요?
개인적으로 성능상에선 문제없을것 같고(static), 읽기편한 코드 관점에서는 그렇게 복잡하지않아서 같이 두어도 괜찮다고 생각이 들어서 안에 놓긴했습니다~

2023-01-20 04:16 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +        DIVIDE("/", (a, b) -> a / b),
수정이 필요할것 같네요~! 각 Operator별 유효성 검증하는걸 Enum에 추가해도 좋을것 같네요. 감사합니다!

2023-01-20 04:16 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +        private final BiFunction<Integer, Integer, Integer> calculationFunction;
아 이거 찾고서 깜빡하고 적용을 안했네요 ㅋㅋ 감사합니다!!

2023-01-20 04:17 UTC, KimJeongHoon3 commented on src/test/java/calculator/CalculatorTest.java
> +        assertEquals("Target must not null or not empty", illegalArgumentException.getMessage());
아름답습니다~~! 이렇게 적용하겠습니다!!

2023-01-21 03:51 UTC, pjhsk113 commented on src/main/java/calculator/CalculatorMain.java
> +        System.out.println(Calculator.calculate(str));
넵, 입력값을 자유롭게 입력하고 계산 결과가 나오는 걸 확인해야하니 필요하다고 생각해요~!

2023-01-21 04:06 UTC, pjhsk113 commented on src/main/java/calculator/Calculator.java
> +    enum Operator {
객체지향 관점에서는 계산기와 연산자는 서로 다른 책임을 가지고 있다고 생각해서 분리하는게 좋다고 생각합니다.
연산자가 계산기의 하위 개념이긴 하지만 Calculator에 모든 기능이 들어있으면 클래스가 너무 커지기도 하고 
기능 확장 시 변경 책임도 2개 이상으로 늘어나기 때문에 분리하는게 좋다고 생각했습니다.

현재 Calculator 클래스는 입력값을 분석하고 Operator에게 연산을 위임하는 흐름을 가지고 있는데, 
분리하면 Calculator와 Operator가 하는 역할이 더 명확히 분리되지 않을까요??

각 클랙스를 모듈화하고 조립해서 최종적으로 `문자열 계산기`를 만든다는 느낌으로 가는게 좋을 것 같아요!

2023-01-21 07:38 UTC, pjhsk113 requested changes

2023-01-21 07:38 UTC, pjhsk113 commented on src/main/java/calculator/Calculator.java
> +        int res = Integer.parseInt(sArr[0]);
[Recommend-Major]
변수명 축약금지!

2023-01-21 12:39 UTC, KimJeongHoon3 commented on src/main/java/calculator/CalculatorMain.java
> +        System.out.println(Calculator.calculate(str));
넵넵! 장호님 코드보고 어떤말씀인지 이해가되었습니다 ㅋㅋ

2023-01-21 12:50 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +    enum Operator {
내부에 있는 enum 클래스를 통해서 객체지향은 이루어졌다고 생각합니다. 현재 연산자가 확장된다해도 변경 책임은 Calculator 와 Operator로 명확하게 나눠져있기에, Operator 한곳에만 변경을 진행하면 되는것 같습니다. HashMap에서 Entry도 이와 비슷한 개념이지않을까 조심스레 생각해봅니다. 
다만, 앞서 말씀드린것처럼 읽기편한 코드냐는 관점에서 지적해주신대로 한 클래스가 너무 커지게되면 보기 불편하기에, 아예 별도로 빼는것도 괜찮을거라는 생각입니다~

2023-01-21 12:51 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +        int res = Integer.parseInt(sArr[0]);
수정하겠습니다!

2023-01-30 04:42 UTC, pjhsk113 approved these changes
따봉 👍👍👍👍👍👍

2023-02-02 01:05 UTC, HwangSeonHo commented on src/main/java/calculator/Calculator.java
> +            int right = Integer.parseInt(sArr[i + 1]);
[Recommend-Request]
result, right보다는 
leftOperand , rightOperand 로 명명하는 것이 좀 더 괜찮지 않을지 의견드립니다.

2023-02-02 01:11 UTC, HwangSeonHo commented on src/main/java/calculator/Calculator.java
> +                .calculate(left, right);
람다 표현식으로 쭉쭉 조합되는게 엄청 명확하고 좋네요 ㅎㅎ 👍

2023-02-02 01:12 UTC, HwangSeonHo approved these changes
👍

2023-02-02 01:17 UTC, pjhsk113 approved these changes

2023-02-02 01:26 UTC, KimJeongHoon3 commented on src/main/java/calculator/Calculator.java
> +            int right = Integer.parseInt(sArr[i + 1]);
@HwangSeonHo 좋은것 같습니다!
그런데 result를 leftOperand 변수를 만들어서 대입할까하다가(`int leftOperand = result`), result 가 왼쪽 피연산자가 되므로 아예 `doCalculate` 메서드 파라미터에서 result 변수가 들어가는 곳 이름을 leftOperand로 주었는데 어떨까요?

2023-02-02 01:42 UTC, KimJeongHoon3 commented
@pjhsk113 장호님! 승인2명 되었습니당~ 머지부탁드려요! :)

2023-02-02 01:44 UTC, merged

2023-02-02 01:49 UTC, HwangSeonHo commented on src/main/java/calculator/Calculator.java
> +            int right = Integer.parseInt(sArr[i + 1]);
int result = Integer.parseInt(values[0]);
요 부분하고 연계되서 그런 것 같은데
딱 이부분만 봤을때는 다른 부분을 보기 전까지 values[0]이 뭐인지 result가 어떤 목적인지 알기 힘들 수도 있을 것 같아서
int result = 초기값; (초기 값이 0이 아니게 만들수도 있으니 설정이나 상수로 빼기 ex 온도계에 계산기 기능을 가져와 사용 10 +1 -1~~)
int firstOperand??? = 메소드에서 최초값빼서 반환해주기 (입력이 왼쪽 부터 빼지 않을 수도 있고 스택으로 받아 올 수도 있고 등등)..
쓰다보니 너무 과하네요 ㅋㅋㅋ 지금도 충분한 것 같습니다